### PR TITLE
Responsive home issue-#133

### PR DESCRIPTION
**Pull request by jaydippatel83**
Sync my code with the merged PR and create a new PR. Please review the code and merge my PR.

### CODE REVIEW

**Comment by jaydippatel83** [comment]
Hey, @marshadkhn can you please provide more details about the testimonial and contact us page? What should I need do change in this section? #133

**Comment by marshadkhn** [comment]
copy contact us and testimonial

**Comment by jaydippatel83** [comment]
update the contact us and testimonial. please check it

**Review by kubical12 — DISMISSED** [review]

**Comment by marshadkhn** [comment]
FireShot Capture 018 - TinDog - supreme-fiesta-576qvqvx69c7wjj-5504 app github dev


Can't see any change

**Comment by marshadkhn** [comment]
Drop a video of your changes

**Comment by jaydippatel83** [comment]
hey, @marshadkhn Update index.html file. please check it. 
here is link: https://www.loom.com/share/d4e61047bee240fea1630988dc6652ea?sid=57c0de7f-1262-4e1e-a63d-a11944644357

**Comment by marshadkhn** [comment]
resolve conflict

**Review by marshadkhn — APPROVED** [review]

**Pull request merged**
