### PR TITLE
Added hover effect on cards

### PR DESCRIPTION
**Pull request by Anshul439**
Added box-shadow and scale effect on cards on hovering

### CODE REVIEW

**Comment by kubical12** [comment]
you should open issue first explaining what changes you want to make , also mention issue number and then send pr 😊

**Comment by kubical12** [comment]
you should first open issue and then your send pr .😊

**Comment by Anshul439** [comment]
It's already opened. Sorry I forgot to mention.
Issue - #110

**Comment by marshadkhn** [comment]
> It's already opened. Sorry I forgot to mention.
> Issue - #110 

Don't open many issues open one big issue and mention all your changes in that it's not a nice approach to just write a single line in issue

**Pull request merged**
